version: '3.8'

services:
  audio-altores:
    image: altores/ai-call-analysis
    container_name: ai-call-analysis
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=${OLLAMA_URL:-http://host.docker.internal:11434/api/generate}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3}
    volumes:
      - /tmp/audio_processing:/tmp/audio_processing
      - app_settings:/app/settings
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  app_settings:
    driver: local 